name: Check Draft Or Blocked

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for 'draft' label
        run: |
          echo "Checking if PR is a draft..."
          if echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | grep -q 'draft'; then
            echo "draft=true" >> $GITHUB_ENV
          else
            echo "draft=false" >> $GITHUB_ENV
          fi

      - name: Check for 'blocked' label
        run: |
          echo "Checking if PR is blocked..."
          if echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | grep -q 'blocked'; then
            echo "blocked=true" >> $GITHUB_ENV
          else
            echo "blocked=false" >> $GITHUB_ENV
          fi

      - name: Fail if PR is a draft or blocked
        if: env.draft == 'true' || env.blocked == 'true'
        run: |
          if [ "${{ env.draft }}" == "true" ]; then
            echo "This PR is currently a draft."
          fi
          if [ "${{ env.blocked }}" == "true" ]; then
            echo "This PR is currently blocked by other feature."
          fi
          exit 1

