name: Check Draft

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-for-draft:
    if: contains(github.event.pull_request.labels.*.name, 'draft')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is a draft
        run: |
          echo "This PR is currently a draft."
          exit 1
  fail-for-blocked:
    if: contains(github.event.pull_request.labels.*.name, 'blocked')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is blocked by other feature
        run: |
          echo "This PR is currently blocked by other feature."
          exit 1
